<?php
/*****NO MOMENTO ESTE ARQUIVO NÃO ESTÁ SENDO UTILIZADO - STAND BY****/
/*
ESTE ARQUIVO CENTRALIZA ALGUMAS CONFIGURAÇÕES DO SITE COMO:
BREADCUMBS,
TITULO DA PÁGINA,
ENTRE OUTROS ITENS A ACRESCENTAR AQUI...
*/

/* CONFIGURAÇÃO DOS BREADCUMBS */

//DEFINO UM IDENTIFICADOR PARA A PÁGINA/ARQUIVO
//UTILIZO O NOME DA URL AMIGAVEL. EX: PÁGINA EMPRESA.PHP É CHAMADA DE EMPRESA



/* AQUI TERMINA A CONFIGURAÇÃO DOS BREADCUMBS */
?>